modLoader="javafml"
loaderVersion="[38,)"
license="All rights reserved"

[[mods]]
    modId="ironchests"
    version="${file.jarVersion}"
    displayName="Iron Chests: Restocked"
    authors="ThatGravyBoat"
    description="Another Iron Chest Mod cause why not?"

[[dependencies.multiloader]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.multiloader]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
